# Generated by Django 5.2.7 on 2026-01-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
