# Generated by Django 5.2.7 on 2026-01-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.pricelist')),
            ],
        ),
    ]
