# Generated by Django 5.2.7 on 2026-01-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_pricelist_category_description_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='title_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='title_zh_hans',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
