# Generated by Django 5.2.7 on 2026-01-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_consultation_title_ar_consultation_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_zh_hans',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
