# Generated by Django 5.2.7 on 2026-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_description_ar_category_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='benefits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='duration',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='procedures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='symptoms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
