# Generated by Django 5.2.7 on 2026-02-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_benefits_category_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='benefits_ar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='benefits_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='benefits_ru',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='benefits_uz',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='benefits_zh_hans',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='full_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='full_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='full_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='full_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='full_description_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='procedures_ar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='procedures_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='procedures_ru',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='procedures_uz',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='procedures_zh_hans',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='symptoms_ar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='symptoms_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='symptoms_ru',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='symptoms_uz',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='symptoms_zh_hans',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
