# Generated by Django 5.2.7 on 2026-01-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.JSONField(max_length=200)),
                ('email', models.JSONField(max_length=200)),
                ('work_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='WorkTime',
        ),
        migrations.RemoveField(
            model_name='homepagestats',
            name='ambulances',
        ),
        migrations.RemoveField(
            model_name='homepagestats',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='homepagestats',
            name='wards',
        ),
        migrations.AddField(
            model_name='homepagestats',
            name='experience',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagestats',
            name='specialists',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagestats',
            name='work_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagestats',
            name='happy_patients',
            field=models.CharField(max_length=100),
        ),
    ]
