# Generated by Django 5.2.7 on 2026-01-29 04:54

import category.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_aboutclinic_delete_email_delete_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='footer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP']), category.utils.check_image_size])),
            ],
        ),
        migrations.CreateModel(
            name='FooterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='footer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP']), category.utils.check_image_size])),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('works', models.JSONField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='footer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP']), category.utils.check_image_size])),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('advantages', models.JSONField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTerapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='footer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP']), category.utils.check_image_size])),
                ('title', models.CharField(max_length=100)),
                ('types', models.JSONField(blank=True, max_length=500, null=True)),
                ('terapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.terapy')),
            ],
        ),
        migrations.DeleteModel(
            name='FooterStats',
        ),
    ]
