# Generated by Django 5.2.7 on 2026-01-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_footerimage_footerpage_terapy_typeterapy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpage',
            name='description_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='description_uz',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='description_zh_hans',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='title_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='works_ar',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='works_en',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='works_ru',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='works_uz',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='works_zh_hans',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='advantages_ar',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='advantages_en',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='advantages_ru',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='advantages_uz',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='advantages_zh_hans',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='description_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='description_uz',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='description_zh_hans',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terapy',
            name='title_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeterapy',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeterapy',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeterapy',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeterapy',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeterapy',
            name='title_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeterapy',
            name='types_ar',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='typeterapy',
            name='types_en',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='typeterapy',
            name='types_ru',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='typeterapy',
            name='types_uz',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='typeterapy',
            name='types_zh_hans',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
    ]
