# Generated by Django 5.2.7 on 2026-01-28 05:44

import category.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_uz', models.CharField(max_length=100, null=True)),
                ('full_name_en', models.CharField(max_length=100, null=True)),
                ('full_name_ru', models.CharField(max_length=100, null=True)),
                ('full_name_zh_hans', models.CharField(max_length=100, null=True)),
                ('full_name_ar', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP']), category.utils.check_image_size])),
                ('profession', models.CharField(max_length=100)),
                ('profession_uz', models.CharField(max_length=100, null=True)),
                ('profession_en', models.CharField(max_length=100, null=True)),
                ('profession_ru', models.CharField(max_length=100, null=True)),
                ('profession_zh_hans', models.CharField(max_length=100, null=True)),
                ('profession_ar', models.CharField(max_length=100, null=True)),
                ('experience', models.IntegerField()),
                ('speciality', models.CharField(max_length=200)),
                ('speciality_uz', models.CharField(max_length=200, null=True)),
                ('speciality_en', models.CharField(max_length=200, null=True)),
                ('speciality_ru', models.CharField(max_length=200, null=True)),
                ('speciality_zh_hans', models.CharField(max_length=200, null=True)),
                ('speciality_ar', models.CharField(max_length=200, null=True)),
                ('operations', models.IntegerField(blank=True, null=True)),
                ('achievements', models.CharField(blank=True, max_length=100, null=True)),
                ('achievements_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('achievements_en', models.CharField(blank=True, max_length=100, null=True)),
                ('achievements_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('achievements_zh_hans', models.CharField(blank=True, max_length=100, null=True)),
                ('achievements_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('about_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('about_en', models.CharField(blank=True, max_length=200, null=True)),
                ('about_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('about_zh_hans', models.CharField(blank=True, max_length=200, null=True)),
                ('about_ar', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
