# Generated by Django 5.2.7 on 2026-01-29 04:38

import category.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality_ar',
            new_name='education_ar',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality_en',
            new_name='education_en',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality_ru',
            new_name='education_ru',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality_uz',
            new_name='education_uz',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality_zh_hans',
            new_name='education_zh_hans',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='about',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='about_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='about_ru',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='about_uz',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='about_zh_hans',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='achievements_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='achievements_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='achievements_ru',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='achievements_uz',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='achievements_zh_hans',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='operations',
        ),
        migrations.AddField(
            model_name='doctor',
            name='works',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='works_ar',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='works_en',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='works_ru',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='works_uz',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='works_zh_hans',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Stickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stickers', models.ImageField(blank=True, null=True, upload_to='stickers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP']), category.utils.check_image_size])),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
            ],
        ),
    ]
