# Generated by Django 5.2.7 on 2026-02-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_speciality_doctor_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='achievements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='institution',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='reception',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.JSONField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education_ar',
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education_en',
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education_ru',
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education_uz',
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education_zh_hans',
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='works',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='works_ar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='works_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='works_ru',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='works_uz',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='works_zh_hans',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
