# Generated by Django 5.2.7 on 2026-02-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_achievements_doctor_full_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='achievements_ar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='achievements_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='achievements_ru',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='achievements_uz',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='achievements_zh_hans',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_bio_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_bio_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_bio_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='institution_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='institution_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='institution_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='institution_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='institution_zh_hans',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services_ar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services_ru',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services_uz',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services_zh_hans',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties_ar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties_ru',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties_uz',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties_zh_hans',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
