# Generated by Django 5.2.7 on 2026-02-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_achievements_doctor_full_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education_ar',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education_en',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education_ru',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education_uz',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education_zh_hans',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
